name: Build Alpaquita Base Image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docker/alpaquita/src/latest_lts.json

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get file properties
        id: image_properties
        uses: ActionsTools/read-json-action@a421f7cef32511e1dde14b2fba3b0dedc435ee6b
        with:
          file_path: "docker/alpaquita/src/latest_lts.json"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push musl
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/alpaquita/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            astarivi/alpaquita:${{ steps.image_properties.outputs.version }}-musl-${{ steps.image_properties.outputs.tag }}
            astarivi/alpaquita:${{ steps.image_properties.outputs.version }}-musl
            astarivi/alpaquita:lts-musl
          build-args: |
            STDLIB=musl
            VERSION=${{ steps.image_properties.outputs.version }}
            RELEASE_X64=${{ steps.image_properties.outputs.releases.musl.x86_64.tag }}
            RELEASE_AARCH64=${{ steps.image_properties.outputs.releases.musl.aarch64.tag }}

      - name: Build and push glibc
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/alpaquita/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            astarivi/alpaquita:${{ steps.image_properties.outputs.version }}-glibc-${{ steps.image_properties.outputs.tag }}
            astarivi/alpaquita:${{ steps.image_properties.outputs.version }}-glibc
            astarivi/alpaquita:lts-glibc
          build-args: |
            STDLIB=glibc
            VERSION=${{ steps.image_properties.outputs.version }}
            RELEASE_X64=${{ steps.image_properties.outputs.releases.glibc.x86_64.tag }}
            RELEASE_AARCH64=${{ steps.image_properties.outputs.releases.glibc.aarch64.tag }}

      - name: Sync README.md
        uses: meeDamian/sync-readme@70e38f5bc63205951219b8e02afb1d6c1f57fa0a
        with:
          user: ${{ secrets.DOCKERHUB_USERNAME }}
          pass: ${{ secrets.DOCKERHUB_PASS }}
          slug: astarivi/alpaquita
          readme: ./docker/alpaquita/README.md
          description: "Alpaquita Linux: a lightweight, high-performance OS optimized for speed and efficiency"