name: Build Alpaquita Base Image

on:
  workflow_dispatch:
    inputs:
      stdlib:
          type: choice
          description: Standard library
          required: true
          options:
          - musl
          - glibc
      version:
        description: Version to use
        required: true
        type: string
      release:
        description: Release number for this version
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/alpaquita/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: astarivi/alpaquita:${{github.event.inputs.version}}-${{ github.event.inputs.stdlib }}-${{github.event.inputs.release}}
          build-args: STDLIB=${{ github.event.inputs.stdlib }},VERSION=${{ github.event.inputs.version }},RELEASE=${{ github.event.inputs.release }}

