name: Check for new Alpaquita Linux versions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-for-updates:
    runs-on: light-executor
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run update script
        run: |
          cd docker/alpaquita/src && python3 release.py -l && python3 release.py -s

      - name: Check for changes
        id: check_changes
        run: |
          changed_files=$(git diff --name-only)

          if echo "$changed_files" | grep -q "docker/alpaquita/src/latest_stream.json"; then
            echo "STREAM_RELEASE=true" >> $GITHUB_ENV
          fi

          if echo "$changed_files" | grep -q "docker/alpaquita/src/latest_lts.json"; then
            echo "LTS_RELEASE=true" >> $GITHUB_ENV
          fi

          if [ -n "$changed_files" ]; then
            echo "CHANGED=true" >> $GITHUB_ENV
          fi

      - name: Configure Git
        run: |
          git config --global user.name "Alpaquita Updates CI"
          git config --global user.email "111199883+astarivi@users.noreply.github.com"

      - name: Push changes
        if: env.CHANGED == 'true'
        run: |
          git add .
          git commit -m "Updated Alpaquita Linux version"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger stream release workflow
        if: env.STREAM_RELEASE == 'true'
        uses: benc-uk/workflow-dispatch@v1.2.4
        with:
          workflow: alpaquita-stream.yml

      - name: Trigger lts release workflow
        if: env.LTS_RELEASE == 'true'
        uses: benc-uk/workflow-dispatch@v1.2.4
        with:
          workflow: alpaquita-lts.yml
